{{- range .Values.swarm.agents }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - {{ .nodeName }} 
      imagePullSecrets: 
        - name: regcred
      containers:
      - name: agent
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }} 
        ports:
        - containerPort: {{ $.Values.port }}
        env:
          - name: AGENT_SECRET
            value: {{ .secret }}
          - name: MACHINE_ID
            value: {{ .machineId }}
        volumeMounts:
          - mountPath: /media/shard
            name: {{ .name }}
            subPath: data
          - mountPath: /data/cubbit
            name: {{ .name }}
            subPath: config
      volumes:
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: "{{ .name }}-data-volume"
{{- end }} 
